globalvar guns, gunsCount;
guns = ds_map_create();
gunsCount = 6;

ds_map_add(guns, "0-ID", 0);
ds_map_add(guns, "0-Name", "Кулак");
ds_map_add(guns, "0-MinDamage", 22);
ds_map_add(guns, "0-MaxDamage", 25);
ds_map_add(guns, "0-CanBeDroped", false);
ds_map_add(guns, "0-CanShoot", false);

ds_map_add(guns, "1-ID", 1);
ds_map_add(guns, "1-Name", "Пистолет");
ds_map_add(guns, "1-MinDamage", 20);
ds_map_add(guns, "1-MaxDamage", 23);
ds_map_add(guns, "1-CanBeDroped", true);
ds_map_add(guns, "1-CanShoot", true);
ds_map_add(guns, "1-ShootCooldown", 16);
ds_map_add(guns, "1-PressToShoot", false);
ds_map_add(guns, "1-AmmoMagazine", 12);
ds_map_add(guns, "1-MaxMagazines", 4);
ds_map_add(guns, "1-ReloadTime", 3 * room_speed);
ds_map_add(guns, "1-BulletSpeed", 14);
ds_map_add(guns, "1-BulletScale", 1);
ds_map_add(guns, "1-BulletDestroyDistance", 540);
ds_map_add(guns, "1-BulletMinRecoil", -3);
ds_map_add(guns, "1-BulletMaxRecoil", 3);
ds_map_add(guns, "1-Bullet", o_Bullet);

ds_map_add(guns, "2-ID", 2);
ds_map_add(guns, "2-Name", "ПП");
ds_map_add(guns, "2-MinDamage", 13);
ds_map_add(guns, "2-MaxDamage", 16);
ds_map_add(guns, "2-CanBeDroped", true);
ds_map_add(guns, "2-CanShoot", true);
ds_map_add(guns, "2-ShootCooldown", 4);
ds_map_add(guns, "2-PressToShoot", true);
ds_map_add(guns, "2-AmmoMagazine", 18);
ds_map_add(guns, "2-MaxMagazines", 5);
ds_map_add(guns, "2-ReloadTime", 3.7 * room_speed);
ds_map_add(guns, "2-BulletSpeed", 23);
ds_map_add(guns, "2-BulletScale", 1);
ds_map_add(guns, "2-BulletDestroyDistance", 780);
ds_map_add(guns, "2-BulletMinRecoil", -10);
ds_map_add(guns, "2-BulletMaxRecoil", 10);
ds_map_add(guns, "2-Bullet", o_Bullet);

ds_map_add(guns, "3-ID", 3);
ds_map_add(guns, "3-Name", "Дробавик");
ds_map_add(guns, "3-MinDamage", 40);
ds_map_add(guns, "3-MaxDamage", 52);
ds_map_add(guns, "3-CanBeDroped", true);
ds_map_add(guns, "3-CanShoot", true);
ds_map_add(guns, "3-ShootCooldown", 30);
ds_map_add(guns, "3-PressToShoot", false);
ds_map_add(guns, "3-AmmoMagazine", 8);
ds_map_add(guns, "3-MaxMagazines", 6);
ds_map_add(guns, "3-ReloadTime", 4.8 * room_speed);
ds_map_add(guns, "3-BulletSpeed", 16);
ds_map_add(guns, "3-BulletScale", 3);
ds_map_add(guns, "3-BulletDestroyDistance", 350);
ds_map_add(guns, "3-BulletMinRecoil", -6);
ds_map_add(guns, "3-BulletMaxRecoil", 6);
ds_map_add(guns, "3-Bullet", o_Bullet);

ds_map_add(guns, "4-ID", 4);
ds_map_add(guns, "4-Name", "Автомат");
ds_map_add(guns, "4-MinDamage", 18);
ds_map_add(guns, "4-MaxDamage", 21);
ds_map_add(guns, "4-CanBeDroped", true);
ds_map_add(guns, "4-CanShoot", true);
ds_map_add(guns, "4-ShootCooldown", 7);
ds_map_add(guns, "4-PressToShoot", true);
ds_map_add(guns, "4-AmmoMagazine", 26);
ds_map_add(guns, "4-MaxMagazines", 5);
ds_map_add(guns, "4-ReloadTime", 4.2 * room_speed);
ds_map_add(guns, "4-BulletSpeed", 20);
ds_map_add(guns, "4-BulletScale", 2);
ds_map_add(guns, "4-BulletDestroyDistance", 1200);
ds_map_add(guns, "4-BulletMinRecoil", -7);
ds_map_add(guns, "4-BulletMaxRecoil", 7);
ds_map_add(guns, "4-Bullet", o_Bullet);

ds_map_add(guns, "5-ID", 5);
ds_map_add(guns, "5-Name", "Револьвер");
ds_map_add(guns, "5-MinDamage", 35);
ds_map_add(guns, "5-MaxDamage", 42);
ds_map_add(guns, "5-CanBeDroped", true);
ds_map_add(guns, "5-CanShoot", true);
ds_map_add(guns, "5-ShootCooldown", 24);
ds_map_add(guns, "5-PressToShoot", false);
ds_map_add(guns, "5-AmmoMagazine", 4);
ds_map_add(guns, "5-MaxMagazines", 6);
ds_map_add(guns, "5-ReloadTime", 4 * room_speed);
ds_map_add(guns, "5-BulletSpeed", 15);
ds_map_add(guns, "5-BulletScale", 2.5);
ds_map_add(guns, "5-BulletDestroyDistance", 1000);
ds_map_add(guns, "5-BulletMinRecoil", -8);
ds_map_add(guns, "5-BulletMaxRecoil", 8);
ds_map_add(guns, "5-Bullet", o_Bullet);